import { useEffect } from 'react';
import { useFamily } from '../lib/FamilyContext';
import {
  BrainCircuit,
  AlertTriangle,
  ShieldCheck,
  Info,
  ArrowRight,
  Loader2 } from
'lucide-react';
import { Avatar } from '../components/Avatar';
import { Link } from 'react-router-dom';

export function AIPredictions() {
  const { activeMember, members, predictions, predictionsLoading, fetchPredictions } = useFamily();

  useEffect(() => {
    fetchPredictions();
  }, [fetchPredictions]);

  const displayPredictions = activeMember ?
  predictions.filter((p) => p.memberId === activeMember.id) :
  predictions;
  // getRiskColor is replaced by getRiskBg below
  const getRiskBg = (level: string) => {
    switch (level) {
      case 'High':
        return 'bg-critical-50 border-critical-100 text-critical-700';
      case 'Moderate':
        return 'bg-warning-50 border-warning-100 text-warning-700';
      case 'Low':
        return 'bg-success-50 border-success-100 text-success-700';
      default:
        return 'bg-slate-50 border-slate-100 text-slate-700';
    }
  };
  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center">
            <BrainCircuit className="w-6 h-6 mr-2 text-primary-600" />
            AI Health Predictions
          </h1>
          <p className="text-slate-500 mt-1">
            Predictive insights based on historical health data analysis.
          </p>
        </div>
      </div>

      <div className="bg-indigo-50 border border-indigo-100 rounded-xl p-4 flex items-start">
        <Info className="w-5 h-5 text-indigo-600 mt-0.5 mr-3 shrink-0" />
        <p className="text-sm text-indigo-800">
          <strong>Disclaimer:</strong> These predictions are generated by AI
          analyzing historical lab trends and are for informational purposes
          only. They do not constitute a medical diagnosis. Always consult a
          healthcare professional.
        </p>
      </div>

      {predictionsLoading ? (
        <div className="flex flex-col items-center justify-center p-12 bg-white rounded-2xl border border-slate-200">
          <Loader2 className="w-10 h-10 text-primary-500 animate-spin mb-4" />
          <h3 className="text-lg font-bold text-slate-900">Analyzing Health Records</h3>
          <p className="text-slate-500 max-w-md text-center mt-2">
            The AI is actively reviewing the medical history and extracting trends to generate accurate predictions. This might take a few seconds.
          </p>
        </div>
      ) : displayPredictions.length > 0 ?
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {displayPredictions.map((prediction) => {
          const member = members.find((m) => m.id === prediction.memberId);
          return (
            <div
              key={prediction.id}
              className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden flex flex-col">
              
                <div className="p-6 border-b border-slate-100">
                  <div className="flex justify-between items-start mb-4">
                    <div>
                      <h2 className="text-xl font-bold text-slate-900">
                        {prediction.condition}
                      </h2>
                      {!activeMember && member &&
                    <div className="flex items-center mt-2">
                          <Avatar
                        name={member.name}
                        src={member.avatarUrl}
                        size="sm"
                        className="w-5 h-5 mr-2" />
                      
                          <span className="text-sm text-slate-600">
                            {member.name}
                          </span>
                        </div>
                    }
                    </div>
                    <div
                    className={`px-3 py-1 rounded-full text-xs font-bold border uppercase tracking-wider ${getRiskBg(prediction.riskLevel)}`}>
                    
                      {prediction.riskLevel} Risk
                    </div>
                  </div>

                  {/* Risk Meter */}
                  <div className="mt-6">
                    <div className="flex justify-between text-xs text-slate-500 mb-1 font-medium">
                      <span>Low</span>
                      <span>Moderate</span>
                      <span>High</span>
                    </div>
                    <div className="h-2 bg-slate-100 rounded-full overflow-hidden flex">
                      <div className="h-full bg-success-400 w-1/3 border-r border-white/50"></div>
                      <div className="h-full bg-warning-400 w-1/3 border-r border-white/50"></div>
                      <div className="h-full bg-critical-400 w-1/3"></div>
                    </div>
                    {/* Indicator triangle */}
                    <div className="relative h-2 mt-1">
                      <div
                      className="absolute top-0 -ml-1.5 text-slate-700"
                      style={{
                        left:
                        prediction.riskLevel === 'Low' ?
                        '16%' :
                        prediction.riskLevel === 'Moderate' ?
                        '50%' :
                        '83%'
                      }}>
                      
                        ▲
                      </div>
                    </div>
                  </div>
                </div>

                <div className="p-6 bg-slate-50 flex-1 flex flex-col gap-6">
                  <div>
                    <h3 className="text-sm font-bold text-slate-900 flex items-center mb-3">
                      <AlertTriangle className="w-4 h-4 mr-2 text-warning-500" />
                      Contributing Factors
                    </h3>
                    <ul className="space-y-2">
                      {prediction.factors.map((factor, idx) =>
                    <li
                      key={idx}
                      className="flex items-start text-sm text-slate-700">
                      
                          <span className="w-1.5 h-1.5 rounded-full bg-slate-400 mt-1.5 mr-2 shrink-0"></span>
                          {factor}
                        </li>
                    )}
                    </ul>
                  </div>

                  <div>
                    <h3 className="text-sm font-bold text-slate-900 flex items-center mb-3">
                      <ShieldCheck className="w-4 h-4 mr-2 text-success-500" />
                      Preventive Suggestions
                    </h3>
                    <ul className="space-y-2">
                      {prediction.suggestions.map((suggestion, idx) =>
                    <li
                      key={idx}
                      className="flex items-start text-sm text-slate-700">
                      
                          <span className="w-1.5 h-1.5 rounded-full bg-success-400 mt-1.5 mr-2 shrink-0"></span>
                          {suggestion}
                        </li>
                    )}
                    </ul>
                  </div>
                </div>

                <div className="p-4 border-t border-slate-200 bg-white flex items-center justify-between">
                  <span className="text-xs text-slate-500">
                    Based on analysis of {prediction.reportCount} reports
                  </span>
                  <Link
                  to="/trends"
                  className="text-sm text-primary-600 font-medium hover:text-primary-700 flex items-center">
                  
                    View Data Trends <ArrowRight className="w-4 h-4 ml-1" />
                  </Link>
                </div>
              </div>);

        })}
        </div> :

      <div className="bg-white rounded-2xl border border-slate-200 p-12 text-center">
          <div className="w-16 h-16 bg-success-50 rounded-full flex items-center justify-center mx-auto mb-4">
            <ShieldCheck className="w-8 h-8 text-success-500" />
          </div>
          <h3 className="text-lg font-bold text-slate-900 mb-2">
            No Significant Risks Detected
          </h3>
          <p className="text-slate-500 max-w-md mx-auto">
            Based on the current medical records, the AI has not detected any
            high-probability health risks for{' '}
            {activeMember ? activeMember.name : 'your family'}. Keep uploading
            reports to maintain accurate monitoring.
          </p>
        </div>
      }
    </div>);

}